export default function CaseDrillDownModal({ cases, selectedCase, onSelectCase, onClose }) {
  const c = selectedCase || cases[0];
  if (!c) return null;

  return (
    <div className="drilldown-modal-overlay" onClick={onClose}>
      <div className="drilldown-modal" onClick={(e) => e.stopPropagation()}>
        {/* Modal Header */}
        <div className="drilldown-modal__header">
          <div>
            <div className="drilldown-modal__tag">INDIVIDUAL CASE DRILL-DOWN · ADMINISTRATIVE RECORD</div>
            <h2 className="drilldown-modal__title">
              Pashu ID: <span className="text-mono">{c.pashuId}</span>
            </h2>
          </div>
          <button className="gov-close-btn" onClick={onClose} aria-label="Close modal">
            ✕
          </button>
        </div>

        {/* Case Selector Tabs if multiple cases */}
        {cases.length > 1 && (
          <div className="drilldown-case-tabs">
            {cases.map((item) => (
              <button
                key={item.id}
                type="button"
                className={`drilldown-tab ${item.id === c.id ? "drilldown-tab--active" : ""}`}
                onClick={() => onSelectCase(item)}
              >
                {item.species.split(" ")[0]} · {item.village} ({item.currentStatus})
              </button>
            ))}
          </div>
        )}

        <div className="drilldown-modal__body">
          {/* AI Preliminary Assessment Callout */}
          <div className="ai-assessment-box">
            <div className="ai-assessment-box__top">
              <span className="ai-tag">AI-ASSISTED PRELIMINARY ASSESSMENT</span>
              <span className="ai-confidence">{c.preliminaryConfidence}</span>
            </div>
            <div className="ai-assessment-box__result">
              <strong>Suspected Disease Pattern:</strong> {c.preliminaryAssessment}
            </div>
            <p className="ai-disclaimer">
              * Official Notice: This is a syndromic preliminary pattern match generated by the system. Clinical diagnosis and treatment protocol are strictly reserved for the assigned Veterinary Officer.
            </p>
          </div>

          {/* Animal & Location Details Grid */}
          <div className="drilldown-grid">
            <div className="drilldown-card">
              <h4 className="drilldown-card__heading">ANIMAL SPECIFICATIONS</h4>
              <div className="info-row">
                <span className="info-lbl">Species / Category:</span>
                <span className="info-val">{c.species}</span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Breed:</span>
                <span className="info-val">{c.breed}</span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Age / Sex:</span>
                <span className="info-val">{c.age} · {c.sex}</span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Owner / Farmer:</span>
                <span className="info-val">{c.farmerName}</span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Reported At:</span>
                <span className="info-val">{new Date(c.reportedAt).toLocaleString("en-IN")}</span>
              </div>
            </div>

            <div className="drilldown-card">
              <h4 className="drilldown-card__heading">LOCATION &amp; FIELD ASSIGNMENT</h4>
              <div className="info-row">
                <span className="info-lbl">District:</span>
                <span className="info-val">{c.district}</span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Taluka:</span>
                <span className="info-val">{c.taluka}</span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Village:</span>
                <span className="info-val">{c.village}</span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Assigned Vet Officer:</span>
                <span className="info-val"><strong>{c.assignedOfficer}</strong></span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Assigned MVU:</span>
                <span className="info-val">{c.mvuAssigned || "None (Post-mortem)"}</span>
              </div>
            </div>
          </div>

          {/* Clinical Presentation & Vaccination History */}
          <div className="drilldown-grid">
            <div className="drilldown-card">
              <h4 className="drilldown-card__heading">OBSERVED CLINICAL SIGNS &amp; SYMPTOMS</h4>
              <div className="symptom-tag-list">
                {c.symptoms.map((s, i) => (
                  <span key={i} className="symptom-pill">
                    {s}
                  </span>
                ))}
              </div>
              <div className="onset-note">
                <strong>Symptom Onset:</strong> {c.symptomOnset}
              </div>
            </div>

            <div className="drilldown-card">
              <h4 className="drilldown-card__heading">VACCINATION HISTORY RECORD</h4>
              <div className="vaccine-history-list">
                {Object.entries(c.vaccinationHistory).map(([vac, status]) => (
                  <div key={vac} className="vac-hist-item">
                    <span className="vac-hist-name">{vac}:</span>
                    <span className={`vac-hist-status ${status.includes("Overdue") || status.includes("Unvaccinated") || status.includes("Not") ? "vac-hist-status--alert" : ""}`}>
                      {status}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Laboratory Status & Clinical Response */}
          <div className="drilldown-card drilldown-card--highlight">
            <h4 className="drilldown-card__heading">LABORATORY INVESTIGATION &amp; CLINICAL RESPONSE</h4>
            <div className="lab-result-section">
              <div className="info-row">
                <span className="info-lbl">Field Visit Status:</span>
                <span className="info-val"><strong>{c.fieldVisitStatus}</strong></span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Sample Status:</span>
                <span className="info-val">{c.sampleStatus}</span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Laboratory Finding:</span>
                <span className="info-val"><strong>{c.labResult}</strong></span>
              </div>
              <div className="info-row">
                <span className="info-lbl">Clinical &amp; Biosecurity Action:</span>
                <span className="info-val">{c.clinicalAction}</span>
              </div>
            </div>
          </div>

          {/* Timeline of Administrative & Field Events */}
          <div className="drilldown-card">
            <h4 className="drilldown-card__heading">RESPONSE EVENT AUDIT TIMELINE</h4>
            <div className="timeline-trail">
              {c.statusTimeline.map((item, idx) => (
                <div key={idx} className="timeline-node">
                  <div className="timeline-node__dot" />
                  <div className="timeline-node__time">{item.time}</div>
                  <div className="timeline-node__label">{item.stage}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="drilldown-modal__footer">
          <button className="btn btn--outline" onClick={onClose}>
            Close Inspection Modal
          </button>
        </div>
      </div>
    </div>
  );
}
